### ISSUE TITLE
locally-provided plugins are not filtered out

### ISSUE THREAD

**Issue by karenetheridge** [dagolden/Dist-Zilla-Plugin-Prereqs-AuthorDeps#1]
The inclusion of a plugin like `[=inc::Foo]` in dist.ini results in a develop prereq on inc::Foo, which can never be satisfied.

I was going suggest that Dist::Zilla::Util::AuthorDeps::extract_author_deps should take a new option to filter out local plugins (short name starting with =) -- but this method cannot know that information -- as the prefix for local plugins and the short -> full name mapping logic is abstracted away in Dist::Zilla::Util::expand_config_package_names.

However, this is not right either -- just because a plugin's short name starts with `=` says nothing about whether it's shipped with the dist or is expected to be installed in the environment - nor should we filter for full names `!~ /^Dist::Zilla::Plugin/`.  What if I shipped a dist with 'Dist/Zilla/Plugin/Foo.pm' in the repository root?

I think the only right answer is something like this:

```
my $authordeps = ... call extract_author_deps as before...
my @final_deps = grep {
    ! -e module_notional_filename($_)  # todo: consider win32 path separator
} @$authordeps;
```

(On the other hand, maybe it would be useful for `authordeps` to have an option to ignore local plugins -- as I know others have complained about `dzil authordeps | cpanm` doing the wrong thing when there are bundled plugins - so should this functionality live there instead?)

Thoughts?

@rjbs

**Comment by van-de-bugger** [comment]
Hi,

Why the bug is closed? Do you mean `exclude` solves the problem? 

Current `exclude` is suitable to be used in `dist.ini` to exclude few manually specified modules.

But it is *not* suitable to use it from within a bundle. In such a case author would likely want to exclude *all* modules from a specific directory. Directory name could be a parameter, and list of modules is not yet known.

I would request an option to exclude all modules matching regexp.
